

package com.college.campusconnect.entity;

import jakarta.persistence.*;
        import lombok.*;
        import java.time.LocalDateTime;

@Entity
@Table(name = "registrations")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Registration {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Link to the User who is registering
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // Link to the Event they are registering for
    @ManyToOne
    @JoinColumn(name = "event_id", nullable = false)
    private Event event;

    private LocalDateTime registrationTime;

    // --- PAYMENT DETAILS ---

    // The Order ID generated by Razorpay when user clicks "Register"
    private String razorpayOrderId;

    // The Payment ID generated by Razorpay AFTER user pays
    private String razorpayPaymentId;

    // Status: "PENDING" (created but not paid), "PAID" (success), "FAILED"
    private String paymentStatus;

    // Amount paid (stored to verify later)
    private double amountPaid;
}